apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: delivery-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8004
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017
            - name: DB_NAME
              value: blinkit
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery-service
  ports:
    - port: 8004
      targetPort: 8004
